// Mock Q&A Templates data
export const qaTemplates = [
  {
    id: '1',
    question: 'Hạn chót nộp đơn là khi nào?',
    answer: 'Tuyển sinh Kỳ Thu 2025: Quyết định Sớm - 15 tháng 11, 2024; Quyết định Thường - 15 tháng 1, 2025; Sinh viên Chuyển trường - 1 tháng 3, 2025',
    category: 'Tuyển Sinh',
    tags: ['hạn chót', 'quan trọng'],
    usageCount: 342,
    lastModified: '2024-10-01',
  },
  {
    id: '2',
    question: 'Có những lựa chọn hỗ trợ tài chính nào?',
    answer: 'Chúng tôi cung cấp học bổng dựa trên thành tích, trợ cấp dựa trên nhu cầu, các khoản vay sinh viên liên bang và các chương trình học tập làm việc. Các gói hỗ trợ tài chính được tùy chỉnh dựa trên hồ sơ học tập và nhu cầu tài chính của bạn.',
    category: 'Hỗ Trợ Tài Chính',
    tags: ['học bổng', 'trợ cấp', 'phổ biến'],
    usageCount: 289,
    lastModified: '2024-09-28',
  },
  {
    id: '3',
    question: 'Làm thế nào để đăng ký tham quan khu học xá?',
    answer: 'Bạn có thể đăng ký tham quan khu học xá thông qua nền tảng tham quan ảo (có sẵn 24/7) hoặc đặt lịch tham quan trực tiếp từ Thứ Hai đến Thứ Sáu, 10 giờ sáng - 4 giờ chiều. Các sự kiện ngày hội đặc biệt được tổ chức vào các ngày thứ Bảy được chọn.',
    category: 'Cuộc Sống Khu Học Xá',
    tags: ['tham quan', 'thăm'],
    usageCount: 201,
    lastModified: '2024-09-25',
  },
  {
    id: '4',
    question: 'Tôi cần GPA bao nhiêu để được nhận?',
    answer: 'Sinh viên được nhận trung bình có GPA là 3.7, nhưng chúng tôi xem xét đơn đăng ký một cách toàn diện. Điểm thi cao, hoạt động ngoại khóa mạnh và bài luận tốt có thể bù đắp cho GPA thấp hơn.',
    category: 'Tuyển Sinh',
    tags: ['yêu cầu', 'gpa'],
    usageCount: 412,
    lastModified: '2024-09-20',
  },
  {
    id: '5',
    question: 'Các chương trình học bổng nào dành cho sinh viên quốc tế?',
    answer: 'Chúng tôi cung cấp học bổng xuất sắc toàn phần, học bổng theo thành tích, và học bổng dành riêng cho sinh viên quốc tế. Số tiền dao động từ 25% đến 100% học phí. Đơn đăng ký học bổng được xem xét tự động khi bạn nộp đơn tuyển sinh.',
    category: 'Hỗ Trợ Tài Chính',
    tags: ['quốc tế', 'học bổng'],
    usageCount: 278,
    lastModified: '2024-10-05',
  },
  {
    id: '6',
    question: 'Yêu cầu về chứng chỉ tiếng Anh là gì?',
    answer: 'Chúng tôi chấp nhận IELTS (tối thiểu 6.5), TOEFL iBT (tối thiểu 85), hoặc Duolingo English Test (tối thiểu 110). Một số chương trình có thể yêu cầu điểm cao hơn. Chứng chỉ phải còn hiệu lực trong vòng 2 năm.',
    category: 'Tuyển Sinh',
    tags: ['tiếng anh', 'yêu cầu', 'chứng chỉ'],
    usageCount: 325,
    lastModified: '2024-09-30',
  },
  {
    id: '7',
    question: 'Có chỗ ở cho sinh viên không?',
    answer: 'Có, chúng tôi cung cấp ký túc xá trên khu học xá với nhiều lựa chọn từ phòng đơn đến phòng đôi. Tất cả phòng đều có Wi-Fi, đồ nội thất cơ bản, và tiện nghi giặt là. Chúng tôi cũng hỗ trợ tìm nhà ở ngoài khu học xá.',
    category: 'Cuộc Sống Khu Học Xá',
    tags: ['ký túc xá', 'chỗ ở'],
    usageCount: 189,
    lastModified: '2024-10-03',
  },
  {
    id: '8',
    question: 'Có cơ hội thực tập không?',
    answer: 'Tất cả các chương trình đều tích hợp cơ hội thực tập. Chúng tôi có quan hệ đối tác với hơn 500 công ty trong nhiều ngành nghề. Trung tâm Nghề nghiệp hỗ trợ sinh viên tìm kiếm và đăng ký thực tập từ năm thứ nhất.',
    category: 'Học Thuật',
    tags: ['thực tập', 'nghề nghiệp'],
    usageCount: 267,
    lastModified: '2024-10-02',
  },
];

// Mock Documents data
export const documents = [
  {
    id: 'D001',
    title: 'Hướng Dẫn Tuyển Sinh 2025',
    description: 'Hướng dẫn đầy đủ về quy trình tuyển sinh, yêu cầu hồ sơ và hạn chót nộp đơn',
    category: 'Tuyển Sinh',
    fileType: 'PDF',
    size: '2.4 MB',
    uploadedDate: '2024-11-01',
    tags: ['hướng dẫn', 'quan trọng'],
    viewCount: 1243,
  },
  {
    id: 'D002',
    title: 'Danh Sách Học Bổng',
    description: 'Tổng hợp tất cả các chương trình học bổng có sẵn với tiêu chí và số tiền',
    category: 'Hỗ Trợ Tài Chính',
    fileType: 'PDF',
    size: '1.8 MB',
    uploadedDate: '2024-10-28',
    tags: ['học bổng', 'tài chính'],
    viewCount: 987,
  },
  {
    id: 'D003',
    title: 'Chương Trình Đào Tạo',
    description: 'Chi tiết về tất cả các chương trình cử nhân và thạc sĩ được cung cấp',
    category: 'Học Thuật',
    fileType: 'PDF',
    size: '3.2 MB',
    uploadedDate: '2024-10-25',
    tags: ['chương trình', 'học thuật'],
    viewCount: 856,
  },
  {
    id: 'D004',
    title: 'Hướng Dẫn Visa Sinh Viên',
    description: 'Quy trình xin visa, tài liệu cần thiết và câu hỏi thường gặp',
    category: 'Dịch Vụ Sinh Viên',
    fileType: 'PDF',
    size: '1.5 MB',
    uploadedDate: '2024-10-20',
    tags: ['visa', 'quốc tế'],
    viewCount: 734,
  },
  {
    id: 'D005',
    title: 'Chính Sách Chuyển Tín Chỉ',
    description: 'Quy định về chuyển tín chỉ từ các trường khác và tương đương khóa học',
    category: 'Học Thuật',
    fileType: 'PDF',
    size: '950 KB',
    uploadedDate: '2024-10-18',
    tags: ['chuyển trường', 'tín chỉ'],
    viewCount: 623,
  },
  {
    id: 'D006',
    title: 'Cuốn Sách Tay Sinh Viên Quốc Tế',
    description: 'Hướng dẫn toàn diện cho sinh viên quốc tế về đời sống, văn hóa và hỗ trợ',
    category: 'Dịch Vụ Sinh Viên',
    fileType: 'PDF',
    size: '4.1 MB',
    uploadedDate: '2024-10-15',
    tags: ['quốc tế', 'hướng dẫn'],
    viewCount: 892,
  },
];

export const categories = ['Tất Cả Danh Mục', 'Tuyển Sinh', 'Hỗ Trợ Tài Chính', 'Cuộc Sống Khu Học Xá', 'Học Thuật', 'Dịch Vụ Sinh Viên'];